# CAS 1 : recherche université
path: ./results/
path_label: ./config/
path_poste: ./config/
path_pays: ./config/
name_path_results: ./results/

# CAS 1 : comparé excels
path_excel: ./results/
name_path_results_excel: ./results/


# parametres
base_donne: pubmed # base de données de recherche
threshold_paper: 2  # nombre de papier à scrapper
mot_clef_coupure: RESULTS # Mot clef de coupure entre 2 chercheurs
threshold_label: 0.75 #ratio de labels à garder : 1 sur 3 tu gardes, 1 sur 5 poubelle
temps_dodo: 5 # temps de pause pour requête ncbi
threshold_ville: 1 # nombre de lettre qui diffère entre 2 villes
threshold_nom: 2 # nombre de lettre qui diffère entre 2 noms
balise_split_end_label: Data
